#version 450

#define BLOCK_SIZE 64
#define KSTRIP_LEN 16
#define INNER_THREAD 16 // inner thread

#define MNSTRIP (BLOCK_SIZE/INNER_THREAD)
#define KSTRIP (KSTRIP_LEN/INNER_THREAD)

#define PER_THREAD (BLOCK_SIZE/INNER_THREAD)

// Experiment Row major VS column major.

layout(binding = 0) readonly buffer Input0{
    float image_data[];
};
layout(binding = 1) readonly buffer Input1 {
    float weight_data[];
};
layout(binding = 2) writeonly buffer Output{
    float outMat_data[];
};

layout(binding = 3) uniform pushBlock {
    int M;
    int K;
    int N;
    int KStrip;
    int KStripRemain;
} p;

shared float ashare[BLOCK_SIZE][KSTRIP_LEN];
shared float bshare[BLOCK_SIZE][KSTRIP_LEN];

layout(local_size_x = INNER_THREAD, local_size_y = INNER_THREAD, local_size_z = 1) in;
void main()
{
    int global_x = int(gl_WorkGroupID.x);
    int global_y = int(gl_WorkGroupID.y);

    int local_x = int(gl_LocalInvocationID.x);
    int local_y = int(gl_LocalInvocationID.y);

    int mIndex = global_x * BLOCK_SIZE;
    int nIndex = global_y * BLOCK_SIZE;

    int aoffset = p.K * mIndex + local_y * p.K + local_x;
    int boffset = nIndex + local_x + local_y * p.N;

//    float panleB[PER_THREAD];

    float sum[PER_THREAD * PER_THREAD];

    for (int n = 0; n < PER_THREAD * PER_THREAD; n++)
    {
        sum[n] = 0.f;
    }

    float panleA[KSTRIP_LEN];
    for (int i = 0; i < p.KStrip; i++)
    {
        // load A and B to SMEM.
//         NOT TRANSPOSE
//        for (int m = 0; m < 2; m++)
//        {
//            int mT = m * INNER_THREAD;
//            for (int n = 0; n < 2; n++)
//            {
//                int nT = n * INNER_THREAD;
//                ashare[mT + local_y][local_x + nT] = image_data[aoffset + mT * p.K + nT + i * KSTRIP_LEN];
//                bshare[mT + local_y][local_x + nT] = weight_data[boffset + nT + mT * p.N + i * KSTRIP_LEN * p.N];
//            }
//        }

//        barrier();

        // The follow code takes about 183 ms.
        // The K is 16, the BLOCK is 64
        for (int m = 0; m < PER_THREAD; m++)
        {
            int panleAOff = (local_y + INNER_THREAD * m);
            for (int wn = 0; wn < KSTRIP_LEN; wn++)
            {
                panleA[wn] = ashare[panleAOff][wn];
            }

            for (int n = 0; n < PER_THREAD; n++)
            {
                for (int j = 0; j < KSTRIP_LEN; j++)
                sum[m*PER_THREAD + n] += panleA[j] * bshare[j][local_x + INNER_THREAD * n];
            }
        }

        barrier();
    }

//    if (p.KStripRemain > 0)
//    {
//        int aoffset2 = aoffset + p.KStrip * KSTRIP_LEN;
//        int boffset2 = boffset + p.KStrip * KSTRIP_LEN * p.N;
//
////        for (int m = 0; m < 2; m++)
////        {
////            int mT = m * INNER_THREAD;
////            for (int n = 0; n < 2; n++)
////            {
////                int nT = n * INNER_THREAD;
////                ashare[mT + local_y][local_x + nT] = image_data[aoffset + mT * p.K + nT + i * KSTRIP_LEN];
////                bshare[mT + local_y][local_x + nT] = weight_data[boffset + nT + mT * p.N + i * KSTRIP_LEN * p.N];
////            }
////        }
//        // load A and B to SMEM.
//        for (int m = 0; m < 2; m++)
//        {
//            int mT = m * INNER_THREAD;
//            for (int n = 0; n < 2; n++)
//            {
//                int nT = n * INNER_THREAD;
//                ashare[mT + local_y][local_x + nT] = image_data[aoffset2 + mT * p.K + nT];
//                bshare[mT + local_y][local_x + nT] = weight_data[boffset2 + nT + mT * p.N];
//            }
//        }
//
//        barrier();
//
////        // change the KStrip to out loop
////        for (int k = 0; k < p.KStripRemain; k++)
////        {
////
////        }
//
////        for (int m = 0; m < PER_THREAD; m++)
////        {
////            for (int wn = 0; wn < KSTRIP_LEN; wn++)
////            {
////                panleA[wn] = ashare[local_y + INNER_THREAD * m][wn];
////            }
////
////            for (int n = 0; n < PER_THREAD; n++)
////            {
////                int sumOffset = m*PER_THREAD + n;
////                for (int j = 0; j < KSTRIP_LEN; j++)
////                    sum[sumOffset] += panleA[j] * bshare[j][local_x + INNER_THREAD * n];
////            }
////        }
//    }

    for (int m = 0; m < PER_THREAD; m++)
    {
        int mIndex2 = mIndex + m * INNER_THREAD + local_y;
        if (mIndex2 < p.M)
        {
            for (int n = 0; n < PER_THREAD; n++)
            {
                int nIndex2 = nIndex + n * INNER_THREAD + local_x;
                if (nIndex2 < p.N)
                {
                    outMat_data[mIndex2 * p.N + nIndex2] = sum[m* PER_THREAD + n];
                }
            }
        }
    }
}
