#version 450
#extension GL_EXT_control_flow_attributes : enable

#define BLOCK_SIZE 128
#define WARP 32
#define ALL_THREAD 256
#define KSTRIP_LEN 16
#define SM_THREAD 32
#define PER_THREAD 8

// Experiment Row major VS column major.

layout(binding = 0) readonly buffer Input0{
    float image_data[];
};
layout(binding = 1) readonly buffer Input1 {
    float weight_data[];
};
layout(binding = 2) writeonly buffer Output{
    float outMat_data[];
};

layout(binding = 3) uniform pushBlock {
    int M;
    int K;
    int N;
    int KStrip;
    int KStripRemain;
} p;

shared float ashare[KSTRIP_LEN][BLOCK_SIZE];
shared float bshare[KSTRIP_LEN][BLOCK_SIZE];

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
void main()
{
    int global_x = int(gl_WorkGroupID.x);
    int global_y = int(gl_WorkGroupID.y);

    int local_x = int(gl_LocalInvocationID.x);
    int local_y = int(gl_LocalInvocationID.y);

    int mIndex = global_x * BLOCK_SIZE;
    int nIndex = global_y * BLOCK_SIZE;

    int aoffset = p.K * mIndex + local_y * p.K + local_x;
    int boffset = nIndex + local_x + local_y * p.N;

    float sum[PER_THREAD][PER_THREAD]; // output = 2x2, 4x4
    for (int m = 0; m < PER_THREAD; m++)
    {
        for (int n = 0; n < PER_THREAD; n++)
        {
            sum[m][n] = 0.f;
        }
    }

    float panleA;
    float panleB[PER_THREAD];

    for (int i = 0; i < p.KStrip; i++)
    {
        // load A and B to SMEM.
        [[unroll]] for (int j = 0; j < 8; j++)
        {
            int j16 = j * 16;
            ashare[local_x][j16 + local_y] = image_data[aoffset + j16 * p.K + i * KSTRIP_LEN];
            bshare[local_y][j16 + local_x] = weight_data[boffset + j16 + i * KSTRIP_LEN * p.N];
        }

        barrier();

        [[unroll]] for (int k = 0; k < KSTRIP_LEN; k++)
        {
            // load smem to reg
            [[unroll]] for (int wn = 0; wn < PER_THREAD; wn++)
            {
                panleB[wn] = bshare[k][local_x + PER_THREAD * wn];
            }

            [[unroll]] for (int m = 0; m < PER_THREAD; m++)
            {
                panleA = ashare[k][local_y + PER_THREAD * m];
                [[unroll]] for (int n = 0; n < PER_THREAD; n++)
                {
                    sum[m][n] += panleA * panleB[n];
                }
            }
        }
        barrier();
    }

    if (p.KStripRemain > 0)
    {
        int aoffset2 = aoffset + p.KStrip * KSTRIP_LEN;
        int boffset2 = boffset + p.KStrip * KSTRIP_LEN * p.N;

        // load A and B to SMEM.
        [[unroll]] for (int j = 0; j < 8; j++)
        {
            int j16 = j * 16;
            ashare[local_x][j16 + local_y] = image_data[aoffset2 + j16 * p.K];
            bshare[local_y][j16 + local_x] = weight_data[boffset2 + j16];
        }

        barrier();

        [[unroll]] for (int k = 0; k < p.KStripRemain; k++)
        {
            // load smem to reg
            [[unroll]] for (int wn = 0; wn < PER_THREAD; wn++)
            {
                panleB[wn] = bshare[k][local_x + PER_THREAD * wn];
            }

            [[unroll]] for (int m = 0; m < PER_THREAD; m++)
            {
                panleA = ashare[k][local_y + PER_THREAD * m];
                [[unroll]] for (int n = 0; n < PER_THREAD; n++)
                {
                    sum[m][n] += panleA * panleB[n];
                }
            }
        }
    }

    [[unroll]] for (int m = 0; m < PER_THREAD; m++)
    {
        int mIndex2 = mIndex + m * PER_THREAD + local_y;
        if (mIndex2 < p.M)
        {
            [[unroll]] for (int n = 0; n < PER_THREAD; n++)
            {
                int nIndex2 = nIndex + n * PER_THREAD + local_x;
                if (nIndex2 < p.N)
                {
                    outMat_data[mIndex2 * p.N + nIndex2] = sum[m][n];
                }
            }
        }
    }
}
