#version 450

#define BLOCK_SIZE 16
#define STRIDE 2

#define STEP (BLOCK_SIZE * STRIDE)

layout(binding = 0) readonly buffer Input0{
    float image_data[];
};
layout(binding = 1) readonly buffer Input1 {
    float weight_data[];
};
layout(binding = 2) writeonly buffer Output{
    float outMat_data[];
};

layout(binding = 3) uniform pushBlock {
    int M;
    int K;
    int N;
    int KStrip;
    int KStripRemain;
} p;

shared float ashare[STEP][STEP];
shared float bshare[STEP][STEP];

layout(local_size_x = BLOCK_SIZE, local_size_y = BLOCK_SIZE, local_size_z = 1) in;
void main()
{
    int local_x = int(gl_LocalInvocationID.x);
    int local_y = int(gl_LocalInvocationID.y);

    int global_x = int(gl_WorkGroupID.x);
    int global_y = int(gl_WorkGroupID.y);

    int mIndex = global_x * STEP;
    int nIndex = global_y * STEP;

    int aoffset = p.K * mIndex;
    int boffset = nIndex;

    vec4 sum = {0.f, 0.f, 0.f, 0.f};
    // TODO! if MxN is not BLOCK,??
    // if Kstrip is not BLOCK ??

    // check if the KStrip is not BLOCK

    int local_y_STRIDE = local_y * STRIDE;
    int local_x_STRIDE = local_x * STRIDE;

    for (int i = 0; i < p.KStrip; i++)
    {
        for (int y = 0; y < STRIDE; y++)
        {
            for (int x = 0; x < STRIDE; x++)
            {
                int local_y_1 = local_y_STRIDE + y;
                int local_x_1 = local_x_STRIDE + x;

                ashare[local_y_1][local_x_1] = image_data[aoffset + i * STEP+local_x_1+local_y_1*p.K];
                bshare[local_y_1][local_x_1] = weight_data[boffset + local_y_1 + i*STEP + local_x_1*p.N];
            }
        }

        barrier();

        for (int y = 0; y < STRIDE; y++)
        {
            for (int x = 0; x < STRIDE; x++)
            {
                for (int k = 0; k < STEP; k++)
                {
                    sum[x*STRIDE + y] += ashare[local_x_STRIDE + x][k] * bshare[local_y_STRIDE + y][k];
                }
            }
        }

        barrier();
    }

    if (p.KStripRemain > 0)
    {
        int aoffset2 = aoffset + p.KStrip * STEP;
        int boffset2 = boffset + p.KStrip * STEP * p.N;

        // NOTE: Calculations beyond the index are meaningless
        for (int y = 0; y < STRIDE; y++)
        {
            for (int x = 0; x < STRIDE; x++)
            {
                int local_y_1 = local_y_STRIDE + y;
                int local_x_1 = local_x_STRIDE + x;

                ashare[local_y_1][local_x_1] = image_data[aoffset2 + local_x_1 + local_y_1 * p.K];
                bshare[local_y_1][local_x_1] = weight_data[boffset2 + local_y_1 + local_x_1 * p.N];
            }
        }

        barrier();

        for (int y = 0; y < STRIDE; y++)
        {
            for (int x = 0; x < STRIDE; x++)
            {
                for (int k = 0; k < p.KStripRemain; k++)
                {
                    sum[x*STRIDE + y] += ashare[local_x_STRIDE + x][k] * bshare[local_y_STRIDE + y][k];
                }
            }
        }
    }

    mIndex += local_x_STRIDE;
    nIndex += local_y_STRIDE;
    int nIndex1 = nIndex + 1;
    int mIndex1 = mIndex + 1;

    if (mIndex < p.M && nIndex < p.N)
        outMat_data[mIndex * p.N + nIndex] = sum[0];

    if (mIndex < p.M && nIndex1 < p.N)
        outMat_data[mIndex * p.N + nIndex1] = sum[1];

    if (mIndex1 < p.M && nIndex < p.N)
        outMat_data[mIndex1 * p.N + nIndex] = sum[2];

    if (mIndex1 < p.M && nIndex1 < p.N)
        outMat_data[mIndex1 * p.N + nIndex1] = sum[3];
    //
    //    // test
    //
    //        if (p.KStripRemain > 0)
    //        {
    //            int aoffset2 = aoffset + p.KStrip * BLOCK_SIZE;
    //            int boffset2 = boffset + p.KStrip * BLOCK_SIZE * p.N;
    //
    //            // NOTE: Calculations beyond the index are meaningless
    //            ashare[local_y][local_x] = image_data[aoffset2 + local_y * p.K + local_x];
    //            bshare[local_y][local_x] = weight_data[boffset2 + local_y + local_x * p.N];
    //
    //            barrier();
    //
    //            for (int k = 0; k < p.KStripRemain; k++)
    //            {
    //                sum += ashare[local_x][k] * bshare[local_y][k];
    //            }
    //        }
    //
    //        mIndex += local_x;
    //        nIndex += local_y;
    //        if (mIndex < p.M && nIndex < p.N)
    //            outMat_data[mIndex * p.N + nIndex] = ashare[local_x][local_y];
}
