#version 450
#define LOCAL_SZ_X 128
layout(binding = 0) readonly buffer Input0{
    float image_data[];
};
layout(binding = 1) readonly buffer Input1 {
    float weight_data[];
};
layout(binding = 2) writeonly buffer Output{
    float outMat_data[];
};

layout(binding = 3) uniform pushBlock {
    int M;
    int K;
    int N;
} p;

layout(local_size_x = LOCAL_SZ_X, local_size_y = 1, local_size_z = 1) in;
void main()
{
    int index = int(gl_GlobalInvocationID.x);

    int gx = index/p.N;
    int gy = index - gx*p.N;
    if(gx < p.M && gy < p.N)
    {
        float sum = 0.0f;

        int image_off = gx * p.K;
        int weight_off = gy;

        for (int i = 0; i < p.K; i++)
        {
            sum += image_data[image_off + i] * weight_data[weight_off + i * p.N];
        }

        outMat_data[gx*p.N + gy] = sum;
    }
}
