#version 450
#define BLOCK_SIZE 16

layout(binding = 0) readonly buffer Input0{
    float image_data[];
};

layout(binding = 1) readonly buffer Input1 {
    float weight_data[];
};

layout(binding = 2) writeonly buffer Output{
    float outMat_data[];
};

layout(binding = 3) uniform pushBlock {
    int M;
    int K;
    int N;
    int KStrip;
    int KStripRemain;
} p;

shared float ashare[BLOCK_SIZE][BLOCK_SIZE];
shared float bshare[BLOCK_SIZE][BLOCK_SIZE];

shared vec4 amatrix[2][BLOCK_SIZE][4];
shared vec4 bmatrix[2][BLOCK_SIZE][4];

layout(local_size_x = BLOCK_SIZE, local_size_y = BLOCK_SIZE, local_size_z = 1) in;
void main()
{
    int local_x = int(gl_LocalInvocationID.x);
    int local_y = int(gl_LocalInvocationID.y);

    int global_x = int(gl_WorkGroupID.x);
    int global_y = int(gl_WorkGroupID.y);

    int mIndex = global_x * BLOCK_SIZE;
    int nIndex = global_y * BLOCK_SIZE;

    int aoffset = p.K * mIndex;
    int boffset = nIndex;

    float sum = 0.;
    // TODO! if MxN is not BLOCK,??
    // if Kstrip is not BLOCK ??

    // check if the KStrip is not BLOCK
    int matrixIndex = local_x/4;
    int inIndex = local_x - matrixIndex*4;

    amatrix[0][local_y][matrixIndex][inIndex] = image_data[aoffset + local_x + local_y * p.K];
    bmatrix[0][local_y][matrixIndex][inIndex] = weight_data[boffset + local_y + local_x * p.N];

    for (int i = 1; i < p.KStrip; i++)
    {
        barrier();
        amatrix[1][local_y][matrixIndex][inIndex] = image_data[aoffset + i * BLOCK_SIZE + local_x + local_y * p.K];
        bmatrix[1][local_y][matrixIndex][inIndex] = weight_data[boffset + local_y + i * BLOCK_SIZE + local_x * p.N];

        sum += dot(amatrix[0][local_x][0],  bmatrix[0][local_y][0]);
        sum += dot(amatrix[0][local_x][1],  bmatrix[0][local_y][1]);
        sum += dot(amatrix[0][local_x][2],  bmatrix[0][local_y][2]);
        sum += dot(amatrix[0][local_x][3],  bmatrix[0][local_y][3]);

        barrier();

        i++;
        if (i < p.KStrip)
        {
            amatrix[0][local_y][matrixIndex][inIndex] = image_data[aoffset + i * BLOCK_SIZE + local_x + local_y * p.K];
            bmatrix[0][local_y][matrixIndex][inIndex] = weight_data[boffset + local_y + i * BLOCK_SIZE + local_x * p.N];
        }

        sum += dot(amatrix[1][local_x][0],  bmatrix[1][local_y][0]);
        sum += dot(amatrix[1][local_x][1],  bmatrix[1][local_y][1]);
        sum += dot(amatrix[1][local_x][2],  bmatrix[1][local_y][2]);
        sum += dot(amatrix[1][local_x][3],  bmatrix[1][local_y][3]);
    }

    if (p.KStripRemain > 0)
    {
        int aoffset2 = aoffset + p.KStrip * BLOCK_SIZE;
        int boffset2 = boffset + p.KStrip * BLOCK_SIZE * p.N;

        // NOTE: Calculations beyond the index are meaningless
        ashare[local_y][local_x] = image_data[aoffset2 + local_x + local_y * p.K];
        bshare[local_y][local_x] = weight_data[boffset2 + local_y + local_x * p.N];

        barrier();

        for (int k = 0; k < p.KStripRemain; k++)
        {
            sum += ashare[local_x][k] * bshare[local_y][k];
        }
    }

    mIndex += local_x;
    nIndex += local_y;

    if (mIndex < p.M && nIndex < p.N)
        outMat_data[mIndex * p.N + nIndex] = sum;
}
