# --- obsensor ---
if(NOT HAVE_OB_SENSOR)
  if(WIN32)
    set(CMAKE_REQUIRED_QUIET TRUE) # for check_include_file
    check_include_file(mfapi.h HAVE_MFAPI)
    if(HAVE_MFAPI)
      set(HAVE_OB_SENSOR TRUE)
      set(HAVE_OB_SENSOR_MSMF TRUE)
      ocv_add_external_target(obsensor "" "" "HAVE_OB_SENSOR;HAVE_OB_SENSOR_MSMF")
    endif()
  elseif(UNIX)
    set(CMAKE_REQUIRED_QUIET TRUE) # for check_include_file
    check_include_file(linux/videodev2.h HAVE_CAMV4L2)
    if(HAVE_CAMV4L2)
      set(HAVE_OB_SENSOR TRUE)
      set(HAVE_OB_SENSOR_V4L2 TRUE)
      ocv_add_external_target(obsensor "" "" "HAVE_OB_SENSOR;HAVE_OB_SENSOR_V4L2")
    endif()
  endif()
endif()
